name: docker scaner
on: push

jobs:
    fuck:
     name: FUCK
     runs-on: ubuntu-latest
     steps:
       - name: Check code
         uses: actions/checkout@v4

       - name: Docker build
         run: docker build -t myapp:latest .
        
       - name: Run Trivy ignoring unfixed vulnerabilities
         run: trivy image --ignore-unfixed --exit-code 1 --severity HIGH,CRITICAL myapp:latest