name: docker scaner
on: push

jobs:
    fuck:
     name: FUCK
     runs-on: ubuntu-latest
     steps:
       - name: Check code
         uses: actions/checkout@v4

       - name: Docker build
         run: docker build -t myapp:latest .
       - name: get wget
         run: sudo apt install -y wget
       - name: get trivy
         run: wget https://github.com/aquasecurity/trivy/releases/download/v0.62.1/trivy_0.62.1_Linux-64bit.deb && sudo dpkg -i trivy_0.62.1_Linux-64bit.deb
       - name: Run Trivy ignoring unfixed vulnerabilities
         run: trivy image --ignore-unfixed --exit-code 1 -f json -o trivy_report.json --severity HIGH,CRITICAL myapp:latest
       - name: save results
         uses: actions/upload-artifact@v4
         with:
          name: trivy-report
          path: trivy_report.json  